export type QuizQuestion = {
    id: string;
    skill: string;
    difficulty: "easy" | "medium" | "hard";
    question: string;
    options: string[];
    correctAnswer: number;
    explanation: string;
};

export const ROLE_QUIZZES: Record<string, QuizQuestion[]> = {
    "Software Engineer": [
        { id: "swe_1", skill: "Data Structures & Algorithms", difficulty: "easy", question: "Which data structure follows the Last-In-First-Out (LIFO) principle?", options: ["Queue", "Stack", "Linked List", "Array"], correctAnswer: 1, explanation: "A Stack follows the LIFO principle where the last element added is the first one removed." },
        { id: "swe_2", skill: "Backend Development", difficulty: "medium", question: "What is the purpose of middleware in an Express.js application?", options: ["To define database schemas", "To handle requests before they reach the route handler", "To serve static HTML files only", "To compile CSS"], correctAnswer: 1, explanation: "Middleware functions have access to the request and response objects and can execute code, modify them, or end the request-response cycle." },
        { id: "swe_3", skill: "System Design", difficulty: "hard", question: "What is 'Sharding' in the context of database scaling?", options: ["Creating read-only replicas", "Caching frequently accessed data", "Horizontal partitioning of data across multiple databases", "Optimizing SQL queries"], correctAnswer: 2, explanation: "Sharding is a method of splitting a large dataset into smaller, more manageable pieces (shards) across multiple database instances." },
        { id: "swe_4", skill: "Data Structures & Algorithms", difficulty: "medium", question: "What is the average time complexity of searching for an element in a balanced Binary Search Tree (BST)?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], correctAnswer: 2, explanation: "In a balanced BST, each comparison eliminates half of the remaining nodes, resulting in logarithmic time complexity." },
        { id: "swe_5", skill: "Frontend Development", difficulty: "easy", question: "Which React hook is used to handle side effects in functional components?", options: ["useState", "useEffect", "useContext", "useMemo"], correctAnswer: 1, explanation: "useEffect tells React that your component needs to do something after render." },
        { id: "swe_6", skill: "Backend Development", difficulty: "hard", question: "Which of the following best describes the 'Event Loop' in Node.js?", options: ["A multi-threaded processing engine", "A single-threaded mechanism that handles asynchronous I/O callbacks", "A database query optimizer", "A way to manage CPU-intensive tasks using clusters"], correctAnswer: 1, explanation: "The event loop allows Node.js to perform non-blocking I/O operations by offloading operations to the system kernel whenever possible." },
        { id: "swe_7", skill: "System Design", difficulty: "medium", question: "What is the primary benefit of using a Load Balancer?", options: ["Encryption of data", "Distributing incoming network traffic across multiple servers", "Increasing database write speed", "Compressing static assets"], correctAnswer: 1, explanation: "Load balancing ensures that no single server bears too much demand, improving responsiveness and availability." },
        { id: "swe_8", skill: "Data Structures & Algorithms", difficulty: "easy", question: "Which of the following is NOT a primitive data type in most programming languages?", options: ["Integer", "Boolean", "String", "Char"], correctAnswer: 2, explanation: "In many lower-level contexts, a String is considered a collection of characters (an array or object) rather than a primitive." },
        { id: "swe_9", skill: "Frontend Development", difficulty: "medium", question: "What is the 'Virtual DOM' in React?", options: ["A direct copy of the browser's DOM", "A lightweight representation of the real DOM used for performance optimization", "A separate window for debugging", "A tool for server-side rendering only"], correctAnswer: 1, explanation: "The Virtual DOM is a programming concept where a 'virtual' representation of a UI is kept in memory and synced with the 'real' DOM." },
        { id: "swe_10", skill: "Backend Development", difficulty: "easy", question: "What does REST stand for?", options: ["Representational State Transfer", "Relational System Task", "Responsive State Technology", "Remote Service Tool"], correctAnswer: 0, explanation: "REST is an architectural style for providing standards between computer systems on the web, making it easier for systems to communicate." }
    ],
    "AI Engineer": [
        { id: "ai_1", skill: "Machine Learning", difficulty: "easy", question: "What is the primary difference between Supervised and Unsupervised learning?", options: ["Supervised uses labeled data; Unsupervised does not", "Unsupervised is faster", "Supervised is only for regression", "There is no difference"], correctAnswer: 0, explanation: "Supervised learning relies on a dataset with known labels (ground truth), while unsupervised learning finds patterns in unlabeled data." },
        { id: "ai_2", skill: "Deep Learning", difficulty: "medium", question: "What is the purpose of an 'Activation Function' in a neural network?", options: ["To initialize weights", "To introduce non-linearity into the output of a neuron", "To calculate the loss", "To normalize the input data"], correctAnswer: 1, explanation: "Without non-linear activation functions, a neural network would just be a linear regression model, regardless of how many layers it has." },
        { id: "ai_3", skill: "MLOps & Deployment", difficulty: "hard", question: "What is 'Model Drift'?", options: ["The weight updates during training", "The degradation of model performance over time due to changes in real-world data distributions", "The process of a model moving from CPU to GPU", "A specific type of data augmentation"], correctAnswer: 1, explanation: "Model drift occurs when the statistical properties of the target variable, which the model is trying to predict, change over time in unforeseen ways." },
        { id: "ai_4", skill: "Mathematical Foundations", difficulty: "medium", question: "What does the 'Gradient Descent' algorithm minimize?", options: ["The accuracy of the model", "The weights of the neural network", "The loss function (error)", "The learning rate"], correctAnswer: 2, explanation: "Gradient descent is an optimization algorithm used to find the values of parameters that minimize a cost function." },
        { id: "ai_5", skill: "Deep Learning", difficulty: "easy", question: "Which type of layer is primarily used in Computer Vision tasks for spatial hierarchy?", options: ["Dense Layer", "Convolutional Layer", "Dropout Layer", "Recurrent Layer"], correctAnswer: 1, explanation: "Convolutional layers automatically and adaptively learn spatial hierarchies of features from input images." },
        { id: "ai_6", skill: "Machine Learning", difficulty: "medium", question: "What is 'Overfitting'?", options: ["When a model performs well on training data but poorly on unseen test data", "When a model is too simple to capture the underlying pattern", "When the training process is too fast", "When the dataset is too large"], correctAnswer: 0, explanation: "Overfitting occurs when the model learns the noise in the training data rather than the actual pattern." },
        { id: "ai_7", skill: "MLOps & Deployment", difficulty: "easy", question: "What is the primary tool used for containerization in MLOps?", options: ["Git", "Docker", "Jenkins", "Pandas"], correctAnswer: 1, explanation: "Docker allows ML teams to package their models and environments into consistent containers for deployment." },
        { id: "ai_8", skill: "Mathematical Foundations", difficulty: "hard", question: "In Linear Algebra, what is an 'Eigenvector'?", options: ["A vector that changes direction when a linear transformation is applied", "A vector that only changes by a scalar factor when a linear transformation is applied", "A vector with a magnitude of zero", "The diagonal elements of a matrix"], correctAnswer: 1, explanation: "An eigenvector of a square matrix is a non-zero vector that remains on the same line after multiplication by the matrix." },
        { id: "ai_9", skill: "Deep Learning", difficulty: "medium", question: "What is 'Backpropagation'?", options: ["A method to initialize neural network weights", "The process of calculating gradients of the loss function with respect to weights", "A type of recurrent neural network", "A data cleaning technique"], correctAnswer: 1, explanation: "Backpropagation is the central mechanism by which neural networks learn, using the chain rule to update weights." },
        { id: "ai_10", skill: "Machine Learning", difficulty: "easy", question: "What is a 'Confusion Matrix' used for?", options: ["Training a model", "Visualizing model performance across different classes", "Generating synthetic data", "Managing database connections"], correctAnswer: 1, explanation: "A confusion matrix is a table used to describe the performance of a classification model on a set of test data for which the true values are known." }
    ],
    "Data Analyst": [
        { id: "da_1", skill: "SQL Proficiency", difficulty: "easy", question: "Which SQL clause is used to group rows that have the same values?", options: ["ORDER BY", "WHERE", "GROUP BY", "HAVING"], correctAnswer: 2, explanation: "GROUP BY is used to arrange identical data into groups." },
        { id: "da_2", skill: "Python for Data", difficulty: "medium", question: "In Pandas, which function is used to read a JSON file into a DataFrame?", options: ["read_csv()", "read_json()", "read_excel()", "to_json()"], correctAnswer: 1, explanation: "Pandas provides the read_json() function specifically for loading JSON data." },
        { id: "da_3", skill: "Data Visualization", difficulty: "easy", question: "Which chart type is best for showing a trend over time?", options: ["Pie Chart", "Bar Chart", "Line Chart", "Scatter Plot"], correctAnswer: 2, explanation: "Line charts are designed to show how data points change over continuous intervals or time." },
        { id: "da_4", skill: "Statistical Analysis", difficulty: "medium", question: "What does the 'Mean' represent in a dataset?", options: ["The most frequent value", "The middle value", "The average value", "The range between max and min"], correctAnswer: 2, explanation: "The mean is calculated by summing all values and dividing by the count of values." },
        { id: "da_5", skill: "SQL Proficiency", difficulty: "hard", question: "What is the difference between WHERE and HAVING in SQL?", options: ["There is no difference", "WHERE filters rows; HAVING filters groups", "HAVING is for SELECT only", "WHERE is for aggregates only"], correctAnswer: 1, explanation: "WHERE is used to filter individual rows before grouping, while HAVING filters groups after the GROUP BY clause." },
        { id: "da_6", skill: "Python for Data", difficulty: "easy", question: "Which library is the foundation for most data analysis tasks in Python?", options: ["Requests", "Django", "Pandas", "PyTest"], correctAnswer: 2, explanation: "Pandas is the core library for data manipulation and analysis in Python." },
        { id: "da_7", skill: "Data Visualization", difficulty: "medium", question: "What is a 'Box Plot' primarily used to show?", options: ["Total counts", "The distribution and outliers of a dataset", "The correlation between two variables", "Hierarchical data"], correctAnswer: 1, explanation: "Box plots provide a visual summary of the median, quartiles, and outliers of a dataset." },
        { id: "da_8", skill: "Statistical Analysis", difficulty: "hard", question: "What is a 'p-value' in hypothesis testing?", options: ["The probability of the null hypothesis being true", "The probability of observing the data given the null hypothesis is true", "The absolute error of the model", "The percentage of missing data"], correctAnswer: 1, explanation: "A p-value measures the strength of evidence against the null hypothesis." },
        { id: "da_9", skill: "SQL Proficiency", difficulty: "medium", question: "Which JOIN returns only the rows where there is a match in both tables?", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN"], correctAnswer: 2, explanation: "INNER JOIN selects records that have matching values in both tables." },
        { id: "da_10", skill: "Python for Data", difficulty: "easy", question: "What is a 'DataFrame' conceptually?", options: ["A list of numbers", "A 2D table-like structure with rows and columns", "A 3D image", "A single scalar value"], correctAnswer: 1, explanation: "Conceptually, a DataFrame is like a spreadsheet or SQL table in memory." }
    ],
    "Product Manager": [
        { id: "pm_1", skill: "Product Strategy", difficulty: "easy", question: "What is a North Star Metric?", options: ["The only metric that matters", "The key measure of success for a product team", "A vanity metric", "Monthly Active Users only"], correctAnswer: 1, explanation: "The North Star Metric is the key measure of success for a product team." },
        { id: "pm_2", skill: "Technical Specs", difficulty: "medium", question: "What does PRD stand for?", options: ["Product Requirement Document", "Project Resource Description", "Primary Rate Design", "Product Roadmap Detail"], correctAnswer: 0, explanation: "A PRD outlines the requirements for a specific product or feature." },
        { id: "pm_3", skill: "Product Analytics", difficulty: "hard", question: "What is 'Cohort Analysis'?", options: ["Analysis of a single user's behavior", "Analysis of users who share a common characteristic over a period of time", "Analysis of profit and loss", "Analysis of server response times"], correctAnswer: 1, explanation: "Cohort analysis helps identify patterns in user behavior by grouping them based on shared traits (e.g., signup month)." },
        { id: "pm_4", skill: "User Perspective", difficulty: "medium", question: "What is the goal of a 'User Interview'?", options: ["To sell the product to the user", "To understand user needs, pain points, and behaviors", "To gather feedback on the PRD only", "To test the production database"], correctAnswer: 1, explanation: "User interviews are a qualitative research method used to gather deep insights into user motivations." },
        { id: "pm_5", skill: "Product Strategy", difficulty: "easy", question: "What does MVP stand for?", options: ["Most Valuable Player", "Minimum Viable Product", "Managed Vision Plan", "Market Value Prediction"], correctAnswer: 1, explanation: "An MVP is a version of a new product which allows a team to collect the maximum amount of validated learning about customers with the least effort." },
        { id: "pm_6", skill: "Technical Specs", difficulty: "hard", question: "Which of the following is usually NOT in a technical specification document?", options: ["System Architecture", "API Endpoints", "Marketing Budget", "Data Schema"], correctAnswer: 2, explanation: "Technical specs focus on the 'how' of implementation, not the business's financial planning." },
        { id: "pm_7", skill: "Product Analytics", difficulty: "medium", question: "What is 'Churn Rate'?", options: ["The speed of development", "The percentage of users who stop using a product during a specific time period", "The number of new features released", "The rate of database queries"], correctAnswer: 1, explanation: "Churn rate is a critical metric for understanding user retention and product-market fit." },
        { id: "pm_8", skill: "User Perspective", difficulty: "easy", question: "What is a 'User Persona'?", options: ["A real person's bio", "A fictional character created to represent a user type", "A type of software bug", "A marketing slogan"], correctAnswer: 1, explanation: "Personas help teams understand and empathize with the target audience." },
        { id: "pm_9", skill: "Product Strategy", difficulty: "medium", question: "What is a 'Product Roadmap'?", options: ["A list of every bug in the system", "A high-level visual summary that maps out the vision and direction of your product offerings over time", "A GPS for delivery trucks", "A set of design mockups"], correctAnswer: 1, explanation: "The roadmap aligns stakeholders and communicates the 'why' and 'what' of the product's future." },
        { id: "pm_10", skill: "Technical Specs", difficulty: "easy", question: "What is a 'User Story'?", options: ["A long biography of a user", "An informal, general explanation of a software feature written from the perspective of the end user", "A collection of error logs", "A design template"], correctAnswer: 1, explanation: "User stories help teams focus on the value provided to the user rather than just technical tasks." }
    ],
    "UX Designer": [
        { id: "ux_1", skill: "User Research", difficulty: "easy", question: "What is the primary goal of User Research?", options: ["To make the UI look pretty", "To understand user needs and behaviors", "To write code faster", "To reduce marketing costs"], correctAnswer: 1, explanation: "User research focuses on understanding user expectations, behaviors, and needs through various qualitative and quantitative methods." },
        { id: "ux_2", skill: "Visual Design", difficulty: "medium", question: "What is 'Typography' in UI design?", options: ["The color palette of the app", "The art and technique of arranging type to make written language legible and appealing", "The layout of image galleries", "The process of resizing buttons"], correctAnswer: 1, explanation: "Typography involves choosing fonts, sizes, and spacing to ensure readability and establish visual hierarchy." },
        { id: "ux_3", skill: "Information Architecture", difficulty: "hard", question: "What is a 'Site Map'?", options: ["A map of the physical office layout", "A visual representation of the relationship between different pages on a website", "A tool for tracking user locations via GPS", "A list of image assets"], correctAnswer: 1, explanation: "A site map helps designers and developers understand the structure and navigation of a product." },
        { id: "ux_4", skill: "Usability Testing", difficulty: "medium", question: "What is 'A/B Testing'?", options: ["Testing only the 'A' version of a site", "Comparing two versions of a webpage or app against each other to determine which one performs better", "A way to test database performance", "An automated code review process"], correctAnswer: 1, explanation: "A/B testing uses data to decide which design or content version achieves higher conversion or engagement." },
        { id: "ux_5", skill: "Visual Design", difficulty: "easy", question: "What does 'Hierarchy' refer to in design?", options: ["The order of files in a folder", "The arrangement of elements in a way that implies importance", "The speed of the server", "The version number of the software"], correctAnswer: 1, explanation: "Visual hierarchy guides the user's eye to the most important parts of the screen first." },
        { id: "ux_6", skill: "User Research", difficulty: "hard", question: "Which method is best for understanding 'why' users behave a certain way?", options: ["Surveys", "Heatmaps", "User Interviews", "Log Analysis"], correctAnswer: 2, explanation: "Qualitative interviews provide deep context and 'why' behind behaviors that quantitative data can't fully capture." },
        { id: "ux_7", skill: "Information Architecture", difficulty: "medium", question: "What is 'Card Sorting'?", options: ["A game played during breaks", "A technique used to design or evaluate the information architecture of a site", "A way to organize CSS files", "A method for prioritizing bugs"], correctAnswer: 1, explanation: "Card sorting involves users grouping information into categories that make sense to them." },
        { id: "ux_8", skill: "Usability Testing", difficulty: "easy", question: "What is a 'Prototype'?", options: ["The final production code", "A preliminary version of a product used to test concepts or processes", "A marketing video", "A detailed project plan"], correctAnswer: 1, explanation: "Prototypes allow for fast iteration and testing before significant resources are spent on full development." },
        { id: "ux_9", skill: "Visual Design", difficulty: "medium", question: "What is 'Whitespace' (or Negative Space)?", options: ["Empty areas in a design that help define structure and focus", "A background color that is always white", "Errors in image rendering", "The space between different files in a code editor"], correctAnswer: 0, explanation: "Whitespace is essential for readability and reducing cognitive load for the user." },
        { id: "ux_10", skill: "User Research", difficulty: "easy", question: "What is the difference between Qualitative and Quantitative research?", options: ["Qualitative is fast; Quantitative is slow", "Qualitative is about 'why'; Quantitative is about 'how many'", "There is no difference", "Quantitative is only for scientific papers"], correctAnswer: 1, explanation: "Qualitative research yields descriptive data, while quantitative research yields numerical and statistical data." }
    ],
    "Cybersecurity Analyst": [
        { id: "cyb_1", skill: "Network Security", difficulty: "easy", question: "What is a Firewall?", options: ["A physical wall in a data center", "A security system that monitors and controls incoming and outgoing network traffic", "A type of database backup", "A high-speed internet cable"], correctAnswer: 1, explanation: "Firewalls act as a barrier between trusted and untrusted networks." },
        { id: "cyb_2", skill: "Threat Analysis", difficulty: "medium", question: "What is 'Phishing'?", options: ["Catching fish with electronic lures", "A fraudulent attempt to obtain sensitive information by disguising as a trustworthy entity", "A way to optimize server ports", "A specific type of encryption"], correctAnswer: 1, explanation: "Phishing is a common social engineering attack used to steal user data." },
        { id: "cyb_3", skill: "SOC Operations", difficulty: "hard", question: "What is a SIEM?", options: ["Security Information and Event Management", "Software Integrated Encryption Module", "System Internal Error Monitor", "Secure Internet Entry Method"], correctAnswer: 0, explanation: "SIEM tools provide real-time analysis of security alerts generated by applications and network hardware." },
        { id: "cyb_4", skill: "Security Compliance", difficulty: "medium", question: "What is the primary goal of the 'GDPR' regulation?", options: ["To regulate crypto mining", "To protect the privacy and personal data of EU citizens", "To ensure all websites use HTTPS", "To govern international domain names"], correctAnswer: 1, explanation: "GDPR is a comprehensive data protection law in the European Union." },
        { id: "cyb_5", skill: "Network Security", difficulty: "easy", question: "What does 'VPN' stand for?", options: ["Virtual Private Network", "Verified Port Node", "Visual Protocol Number", "Variable Processing Notification"], correctAnswer: 0, explanation: "A VPN extends a private network across a public network and enables users to send and receive data as if their computing devices were directly connected to the private network." },
        { id: "cyb_6", skill: "Threat Analysis", difficulty: "hard", question: "What is a 'Zero-Day Vulnerability'?", options: ["A bug that is fixed within zero days", "An undisclosed computer-software vulnerability that hackers can exploit before the vendor has a patch", "A vulnerability that only exists on Sundays", "A minor UI bug"], correctAnswer: 1, explanation: "Zero-day attacks occur before the developer is even aware of the vulnerability." },
        { id: "cyb_7", skill: "SOC Operations", difficulty: "medium", question: "What is the purpose of an 'Intrusion Detection System' (IDS)?", options: ["To block all incoming traffic", "To monitor a network or systems for malicious activity or policy violations", "To speed up data transfers", "To generate random passwords"], correctAnswer: 1, explanation: "An IDS alerts administrators when it detects suspicious behavior." },
        { id: "cyb_8", skill: "Security Compliance", difficulty: "easy", question: "What is 'Multi-Factor Authentication' (MFA)?", options: ["Using multiple monitors for security", "A security system that requires more than one method of authentication from independent categories of credentials", "A way to encrypt multiple files at once", "A type of physical lock"], correctAnswer: 1, explanation: "MFA adds extra layers of security to verify the user's identity." },
        { id: "cyb_9", skill: "Threat Analysis", difficulty: "medium", question: "What is 'Ransomware'?", options: ["Software that improves computer performance", "Malware that threatens to publish the victim's data or block access to it unless a ransom is paid", "A tool for recovering deleted files", "A type of free antivirus"], correctAnswer: 1, explanation: "Ransomware often uses encryption to hold the victim's data hostage." },
        { id: "cyb_10", skill: "Network Security", difficulty: "easy", question: "What does 'HTTPS' stand for?", options: ["Hypertext Transfer Protocol Secure", "High Tech Program System", "Host Type Tracking Screen", "Hyperlink Text Protocol Standard"], correctAnswer: 0, explanation: "HTTPS is an extension of HTTP used for secure communication over a computer network." }
    ]
};
