import * as React from "react";
import { Sparkles, TrendingUp, Target, Loader2, AlertCircle } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { getDashboardInsights, type DashboardInsightsResponse } from "@/services/mentorApi";

/**
 * AI-Powered Dashboard Insights
 * 
 * Displays personalized progress summary and recommendations
 * generated by the AI Mentor based on user's current skills and goals.
 */
export function AIDashboardInsights() {
    const [insights, setInsights] = React.useState<DashboardInsightsResponse | null>(null);
    const [loading, setLoading] = React.useState(true);
    const [error, setError] = React.useState<string | null>(null);

    React.useEffect(() => {
        loadInsights();
    }, []);

    async function loadInsights() {
        setLoading(true);
        setError(null);

        try {
            const data = await getDashboardInsights();
            setInsights(data);
        } catch (err: any) {
            console.error("Failed to load insights:", err);
            setError(err.message || "Unable to load insights");
        } finally {
            setLoading(false);
        }
    }

    if (loading) {
        return (
            <Card className="rounded-3xl border-slate-200 bg-gradient-to-br from-blue-900 to-indigo-600 p-8 text-white shadow-lg">
                <div className="flex items-center justify-center gap-3 py-8">
                    <Loader2 className="h-6 w-6 animate-spin text-blue-200" />
                    <span className="text-sm font-medium text-blue-100">
                        Your mentor is analyzing your progress...
                    </span>
                </div>
            </Card>
        );
    }

    if (error || !insights) {
        return (
            <Card className="rounded-3xl border-slate-200 bg-slate-50 p-8 shadow-sm">
                <div className="flex items-start gap-3">
                    <AlertCircle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
                    <div>
                        <p className="text-sm font-medium text-slate-900">Insights Unavailable</p>
                        <p className="text-xs text-slate-500 mt-1">
                            {error || "We're updating your progress analysis. Check back in a moment."}
                        </p>
                        <button
                            onClick={loadInsights}
                            className="mt-3 text-xs font-semibold text-blue-900 hover:underline"
                        >
                            Try Again
                        </button>
                    </div>
                </div>
            </Card>
        );
    }

    return (
        <Card className="rounded-3xl border-none bg-gradient-to-br from-blue-900 to-indigo-600 p-8 text-white shadow-2xl">
            {/* Header */}
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-blue-300 mb-6">
                <Sparkles className="h-4 w-4" />
                AI Mentor Insights
            </div>

            {/* Progress Overview */}
            <div className="mb-6">
                <div className="flex items-end justify-between mb-2">
                    <div className="text-sm font-medium text-blue-100">Overall Readiness</div>
                    <div className="text-2xl font-bold">{insights.progressPercent}%</div>
                </div>
                <Progress value={insights.progressPercent} className="h-2 bg-white/10" />
            </div>

            {/* AI Summary */}
            <div className="mb-6 rounded-2xl bg-white/5 border border-white/10 p-5">
                <div className="text-sm leading-relaxed text-blue-50">
                    {insights.summary}
                </div>
            </div>

            {/* Focus Area */}
            <div className="mb-6 flex items-start gap-3">
                <div className="rounded-xl bg-amber-500/20 p-2">
                    <Target className="h-4 w-4 text-amber-300" />
                </div>
                <div className="flex-1">
                    <div className="text-[10px] uppercase font-bold tracking-wider text-amber-300 mb-1">
                        Current Focus
                    </div>
                    <div className="text-sm font-semibold text-white capitalize">
                        {insights.focusArea.replace(/-/g, " ")}
                    </div>
                </div>
            </div>

            {/* Next Action */}
            <div className="rounded-2xl bg-white/10 border border-white/20 p-5">
                <div className="flex items-start gap-3">
                    <TrendingUp className="h-5 w-5 text-emerald-300 flex-shrink-0 mt-0.5" />
                    <div>
                        <div className="text-[10px] uppercase font-bold tracking-wider text-emerald-300 mb-1">
                            Next Best Action
                        </div>
                        <div className="text-sm text-blue-50">
                            {insights.nextAction}
                        </div>
                    </div>
                </div>
            </div>
        </Card>
    );
}
